### ISSUE TITLE
allow specify nt_features and nt_distances with partial name rather than a vector?

### ISSUE THREAD

**Issue by venpopov** [venpopov/bmm#102]
Could be nice instead of having to fully write the vector of column names for non_target features and distances, to be able to just specify the prefix of columns, and we get them internally via "grepl". Logic in the data check would be:

- check if nt_features or nt_distances match existing column names - continue as usual
- if not, check if grepl matches existing column names - if so, get those column names and continue as usual
- if both return null, give the current error

not high priority, but nice to have

**Comment by GidonFrischkorn** [comment]
I like this idea. In princinple, if users provide the character part of the variables, then we could infer it assuming that they would always start from 1 and then go-on until `max(setsize)-1`. We could allow to only provide a single character to be pased to `nt_features` and `nt_distances`, but still throw a warning that we assume that they used the above mentioned numbering scheme at the end of the provided character.

With some regex syntax the user might even specify something like `nt*_col` with the * reflecting the integers indicating the non-target identifier. But this would still, require some instructions, that we could probably add to the documentation.

**Comment by venpopov** [comment]
we don't have to assume how the numbering goes. we can just extract all columns that contain the character part

I like the idea of the regex syntax also
