### ISSUE TITLE
change license to GPL

### ISSUE THREAD

**Issue by venpopov** [venpopov/bmm#116]
Since we use a few copy-pasted functions from `brms`, which is licensed under GPL-2, we also need to have the same license (as explained here https://r-pkgs.org/license.html#sec-code-you-bundle). Just noting the license and copyright for the brms-misc.R file is not enough. And we should do it before anyone else contributes code, because after that we'll have to confirm with them if we want to change the license.

**Comment by GidonFrischkorn** [comment]
Thanks for noting this and I have no problem with adjusting the license. This is maybe something we should also discuss with Paul when we are visiting him in May.
