### ISSUE TITLE
add a message upon loading the package

### ISSUE THREAD

**Issue by venpopov** [venpopov/bmm#117]
for example, when you load brms, you get the following message:

```
Loading 'brms' package (version 2.20.12). Useful instructions
can be found by typing help('brms'). A more detailed introduction
to the package is available through vignette('brms_overview').
```

we should add something like that for our package. We also need to update bmm-package.R, which generates help('bmm') - currently it's automatically generate with very little info

**Comment by GidonFrischkorn** [comment]
Yes, we should update this and I also like having a message when you load the package.

**Comment by GidonFrischkorn** [comment]
I have had a quick look into this and think it should not be too complicated. But then I thought we might want to discuss, if there are some default settings that we want to set when the package is loaded. For example, setting the option `bmm.default_prior = TRUE`. So, I thought we should quickly discuss what this should include in addition to the startup Message.

**Comment by venpopov** [comment]
we don't need to set that - in all the models we have a line:

```
  if (getOption("bmm.default_priors", TRUE)) {
```

which gives TRUE if the option is not found, as is the case if the user has not specified it. I think that's how most packages handle default settings

but yes, we can discuss what we want to include in the message and if anything else
