### ISSUE TITLE
should we load brms automatically when bmm is loaded?

### ISSUE THREAD

**Issue by venpopov** [venpopov/bmm#118]
Related to this issue, which we resolved by having an explicit alias for save_pars: https://github.com/venpopov/bmm/pull/110

Since `brms` is the main workhorse behind the `bmm` package, should we make it so that it is loaded automatically when loading `bmm`? This can be done by including it in `depends` rather than `imports`. `brms` does this with `Rcpp`. 

This will avoid having issues like the one above in the future (and we can actually just remove the save_pars alias if we do this).

If we do this, this is what happens when you load `bmm`:

![image](https://github.com/venpopov/bmm/assets/12783882/c295e1dc-e080-462d-b5ad-7e297160e1de)

What do you think?

**Comment by GidonFrischkorn** [comment]
I have been thinking about this, too. And generally I think there are many reasons to do so, especially because most of the post-processing is still relying on `brms` functions and if `brms` were loaded automatically users do not have to worry about loading `brms` to use these functions.

**Comment by venpopov** [comment]
OK, I'll add this and remove the save_pars alias
