### ISSUE TITLE
potential error in IMMfull formula?

### ISSUE THREAD

**Issue by venpopov** [venpopov/bmm#12]
Line 420 of fit_model specifies that for IMMfull

`      brms::nlf(theta1 ~ c) +`

Shouldn't it be 

`      brms::nlf(theta1 ~ c + a) + `

That's the equation in Oberauer (2017), and its also correctly specified in IMMabc. I suspect that because the IMMbsc model does not have an a parameter, this was a copying mistake. Or am I misunderstanding something?

And if it is an error, that would mean the Example5 estimates in the tutorial and the corresponding figure are incorrect and we would need to fix and update the manuscript

**Comment by GidonFrischkorn** [comment]
Yes, I checked this and corrected the error in the IMMfull formula.
