### ISSUE TITLE
simplify structure of .model_*

### ISSUE THREAD

**Issue by venpopov** [venpopov/bmm#149]
Currently we have:

```
   out <- list(
      resp_vars = nlist(resp_err),
      other_vars = nlist(),
      info = list(
         domain = 'Visual working memory',
         task = 'Continuous reproduction',
         name = 'Signal Discrimination Model (SDM) by Oberauer (2023)',
         citation = paste0('Oberauer, K. (2023). Measurement models for visual working memory - ',
                           'A factorial model comparison. Psychological Review, 130(3), 841-852'),
         version = 'Simple (no non-targets)',
         requirements = '- The response variable should be in radians and represent the angular error relative to the target',
         parameters = list(
            mu = 'Location parameter of the SDM distribution (in radians; by default fixed internally to 0)',
            c = 'Memory strength parameter of the SDM distribution',
            kappa = 'Precision parameter of the SDM distribution (log scale)'
         ),
         links = list(mu = 'identity',
                      c = 'log',
                      kappa = 'log'),
         fixed_parameters = list(
            mu = 0
         )),
      void_mu = FALSE
   )
```

I propose we remove the "info" subset and unpack it as:

```
  out <- list(
    resp_vars = nlist(resp_err),
    other_vars = nlist(),
    domain = 'Visual working memory',
    task = 'Continuous reproduction',
    name = 'Signal Discrimination Model (SDM) by Oberauer (2023)',
    citation = paste0(
      'Oberauer, K. (2023). Measurement models for visual working memory - ',
      'A factorial model comparison. Psychological Review, 130(3), 841-852'
    ),
    version = 'Simple (no non-targets)',
    requirements = '- The response variable should be in radians and represent the angular error relative to the target',
    parameters = list(mu = 'Location parameter of the SDM distribution (in radians; by default fixed internally to 0)',
                      c = 'Memory strength parameter of the SDM distribution',
                      kappa = 'Precision parameter of the SDM distribution (log scale)'),
    links = list(mu = 'identity',
                 c = 'log',
                 kappa = 'log'),
    fixed_parameters = list(mu = 0),
    void_mu = FALSE
  )
```

it will simplify a bunch of the code when accessing elements of a fitted object (i just had to write fit$bmm$model$info$parameters and got annoyed 

thoughts @GidonFrischkorn ?

**Comment by GidonFrischkorn** [comment]
I totally see your point and agree that we can simplify the `bmmmodel` structure. Maybe we can still retain the `info` list but only leave the descriptive information in it (domain, task, name, citation, requirements). That way `info` will contain resources for documenting the most important aspects of the model. 

But all information that we do interact with (links, parameters, fixed_parameters, void_mu, etc.)  when setting up the model should be in separate entries of the list. If you prefer, we can also unpack everything. I just thought maybe having a `print_info` function could make use of all the info being stored in one entry of the list. But then again, it would also be easy to just collect a set of consistently named entries. So, in the end it won't make a big difference.

**Comment by venpopov** [comment]
we already have the model_info info which prints that https://github.com/venpopov/bmm/blob/5d28b34a5092ccca120c532758be07496b6c7339/R/helpers-model.R#L254

but we have to handle each part manually because the printing is different for different components, so we don't gain anything by having it separated out into an info subcomponent.

I'll add this change to the summary PR
