### ISSUE TITLE
why are there values for all non-targets in OberauerLin_2017 for different setsizes

### ISSUE THREAD

**Issue by venpopov** [venpopov/bmm#153]
I just realized that in the OberauerLin_2017 dataset, we have values in all non-target columns even when the setsize is smaller. E.g., even for setsize 1, we have values for non-targets. This was also in the old dataset before I reformatted it a month ago. Am I missing something, or should there be NAs?

![image](https://github.com/venpopov/bmm/assets/12783882/8ade00fd-16b6-4cd3-bce4-3f08078ae063)

**Comment by venpopov** [comment]
I looked at the documentation here: https://osf.io/j24wb
And it says that the remaining values were ignored.
I think we should code them as NA, for consistency and to avoid confusion.

**Comment by GidonFrischkorn** [comment]
Agreed. Sorry for not clarifying that these values were ignored when documenting the dataset.

**Comment by venpopov** [comment]
No need for sorry, I also didn't notice until now :)

**Comment by GidonFrischkorn** [comment]
But I was aware of it when working with the data set, but never expilicitly documented it. And probably I should have taken care of that given that we also use the data for the tutorial paper.

Anyway, good that we can take care of that now.
