### ISSUE TITLE
some useful resources and channels of communication

### ISSUE THREAD

**Issue by bnicenboim** [venpopov/bmm#164]
Hi,
This is not really an issue, (it would be good if you open the Discussion section in github, see it in my own package: https://github.com/bnicenboim/eeguana/discussions). 

It might be useful to take a look at the following resources:
https://github.com/spinkney/helpful_stan_functions  (many useful functions)
https://ropensci.org/ (to get review and some context for a package)

Ok, that's it for now, I have a million deadlines, I'll probably get back to this in a couple of months with my own models... (it's just that this is much more fun :) )

**Comment by venpopov** [comment]
Opening a Discussion section sounds like a good idea to keep the issues section for things that need actions on the code. Let us discuss it, but in general I don't see why not.

I know what you mean about the last sentence - we've been having a lot of fun working on this and sometimes it is difficult to get back to other things that need attention :)

**Comment by venpopov** [comment]
I opened the Discussions section as suggested :)
