### ISSUE TITLE
[bug] `sd` for `thetant` for setsize = 1 not fixed to zero in `mixture3p`

### ISSUE THREAD

**Issue by GidonFrischkorn** [venpopov/bmm#202]
**Describe the bug**
When working on the revisions of the tutorial paper I noticed that when we estimate the `mixture3p` using random effects for the `set_size` variable that there are still random effects estimated for `thetant` for set size = 1. See screenshot below

![image](https://github.com/venpopov/bmm/assets/17825471/a46379d9-219f-488e-bfac-771d23e0092d)

**To Reproduce**
You can see the specified call to `bmm` in the screenshot of the summary. 

**Expected behavior**
Ideally, we should fix the `sd` to zero and list them under `Constant Parameters`. But I do not know if this is possible via priors. There might be constraint that `sd` parameters cannot be fixed to zero, but only a value very close to zero.

**Comment by GidonFrischkorn** [comment]
I checked this again, and it actually is not a serious problem, as all non-target mixtures are switched off using the Index-Coding we implemented. So, likely the estimated `sd` in these model just represents samples from the prior. The same happens in the `imm` models for the `a` and `s` parameters for set size = 1

**Comment by venpopov** [comment]
Yes, I noticed that some time ago but concluded the same that it's not a problem because we turn the effects off. It could still be confusing to users, so I'll see if there's an easy way to fix those to a constant too

**Comment by venpopov** [comment]
it was an easy solve, PR is up
