### ISSUE TITLE
[feature-request] Non-Linear Formulas are not yet supported for `set_default_prior`

### ISSUE THREAD

**Issue by GidonFrischkorn** [venpopov/bmm#231]
With the addition of the `configure_prior` method and the associated `set_default_prior` function, it is no longer straightforward to use non-linear formulas with `bmmodels`.

Even, when you try to provide default_priors for `nlpars` the function. Currently, you can only pass priors that are added to the default_priors generated by `set_default_prior`. But in case of a non-linear formula like below the `set_default_prior` attempts to also set priors for non-linear parameters. However, these can currently not be provided.

```r
data <- oberauer_lin_2017

formula <- bmmformula(
  c ~ endC  - inv_logit(pStart) * endC * exp(-log(slope) + (set_size-1)),
  kappa ~ 1 + (1 | ID),
  pStart ~ 1 + (1 | ID),
  endC ~ 1 + (1 | ID),
  slope ~ 1 + (1 | ID)
)

model = sdm(resp_error = "dev_rad",
            priors = list(pStart = list(main = "normal(0,1)", effect = "normal(0,1)"),
                         endC = list(main = "normal(0,1)", effect = "normal(0,1)"),
                         slope = list(main = "normal(0,1)", effect = "normal(0,1)")))

default_prior(formula,
              data_sorted,
              model)
```

I ran into a similar problem with the `m3_custom` model. There the model parameters are defined by the users in the activation functions for all response categories. Therefore the `check_model` method checks which parameters are defined and adds them to the model object.

```r
check_model.m3_custom <- function(model, data = NULL, formula = NULL) {
   existing_par_names <- names(model$parameters)
   
   user_pars <- rhs_vars(formula[is_nl(formula)])
   user_pars <- user_pars[-which(user_pars %in% names(formula[is_nl(formula)]))]
   user_pars <- user_pars[which(!user_pars %in% names(model$parameters))]
   if (length(user_pars > 0)) {
      model$parameters <- append(model$parameters, user_pars)
      names(model$parameters) <- c(existing_par_names,user_pars)
   }

   # add link functions if missing
   stopif(length(model$links) < (length(model$parameters) - 1),
          glue("You have not provided link functions for any of the specified parameters.\n",
               "Please provide link functions for all model parameters to ensure proper identification \n",
               "of your model"))

   # add default priors if missing
   missing_priors <- names(model$parameters[which(!model$parameters %in% names(model$default_priors))])
   missing_priors <- missing_priors[which(!missing_priors %in% names(model$fixed_parameters))]
   warnif(length(missing_priors) > 0 && getOption("bmm.default_priors"),
          glue("You have not provided default_priors for at least one parameter in the model.\n",
               "Default priors will be specified internally based on the provided link function.\n",
               "Please check if the used priors are reasonable for your application"))
   for (m in missing_priors) {
      if (model$links[[m]] ==  "log") {
         prior <- list(main = "normal(1,1)", effect = "normal(0,0.5)")
      } else if (model$links[[m]] ==  "identity") {
         prior <- list(main = "normal(0,1)", effect = "normal(0,1)")
      } else if (model$links[[m]] == "logit") {
         prior <- list(main = "normal(0,1)", effect = "normal(0,1)")
      } else {
         stop2(glue("Invalid link function provided!\n",
                    "Please use one of the following link functions: identity, log, logit"))
      }
      model$default_priors[[m]] <- prior
   }

   NextMethod("check_model")
}
```

I have also adapted the call to the `m3` model so that users can pass `default_priors` for the user defined model parameters via the `...`. I think, we should be able to adapt this and evaluate if the `...` contain `default_priors` and then add them to the `default_priors` we coded in the model call.

**Comment by GidonFrischkorn** [comment]
Here is a proposition to add user specified `default_priors` to the model object:

```
 # add default_priors if passed to dots
  if(!is.null(dots$default_priors)){
    user_default_priors <- names(dots$default_priors)
    bmm_default_priors <- names(out$default_priors)
    out$default_priors <- c(out$default_priors[!(bmm_default_priors %in% user_default_priors)],dots$default_priors)
  }
```

**Comment by GidonFrischkorn** [comment]
But I think, we actually have to remove the `default_priors` for model parameters that have been predicted by a non-linear formula. So, in the example above the `default_prior` for `c` would have to be dropped from `model$default_priors`, if I understand the `set_default_prior` function correctly.

Also, if I see this correctly, this is something that we have to consider for all `bmmodels` currently implemented in the package.

**Comment by GidonFrischkorn** [comment]
I have pushed some edits on a new branch `priors_nlformula` and linked it to this issue. But I still did not get the `sdm` to run as there is some issue with the compilation.

**Comment by venpopov** [comment]
This went a little above my head right now. Perhaps you can explain what the problem is in person on Monday?

Btw, this has no reason to work:

```r
model = sdm(resp_error = "dev_rad",
            priors = list(pStart = list(main = "normal(0,1)", effect = "normal(0,1)"),
                         endC = list(main = "normal(0,1)", effect = "normal(0,1)"),
                         slope = list(main = "normal(0,1)", effect = "normal(0,1)")))
```

There is no `priors` argument to `sdm()`. Priors from users should be provided by the typical way for brms.

**Comment by GidonFrischkorn** [comment]
Sure, we can chat on Monday. But I am only in until lunchtime, and have some meetings. So, I will probably not have a lot of time.

**Comment by venpopov** [comment]
Ok, I think I understand the issue. A simpler example:

```r
default_prior(
  formula = bmmformula(c ~ exp(nlc), nlc ~ 1),
  data = oberauer_lin_2017,
  model = sdm(resp_error = "dev_rad")
)
```

This doesn't run because we currently try to set a default prior on c. Your change for check_model() seems like it should solve that. Does it not?

**Comment by GidonFrischkorn** [comment]
Yes, the simple example runs.

But the more complicated non-linear formula that includes a predictor `set_size` from the data leads to a compilation error for STAN. I have to check if this is a problem with the formula that I specified or if there is a more complicated issue with respect to using variables from the data in non-linear formulas.

**Comment by venpopov** [comment]
Possibly because set_size is a factor in the oberauer_lin_2017 dataset?

**Comment by GidonFrischkorn** [comment]
[like]  Gidon Frischkorn-Bartsch reacted to your message:
________________________________

**Comment by GidonFrischkorn** [comment]
Yes, that was it. I will check through the changes that I made and take care that there are no unnecessary edits in the code and the make a pull request.

I wondered, if we should also print a warning if a non-linear formula for one of the model parameters is used that priors should be specified manually by the user. What do you think?

**Comment by venpopov** [comment]
I like it!
