### ISSUE TITLE
Make the different data generating functions consistent 

### ISSUE THREAD

**Issue by venpopov** [venpopov/bmm#31]
For each of the models, we should make the data simulation/generation functions consistent in the parameters they take and the output they provide.

We should also simplify them and split into parts. We should have simple functions equivalent to rnorm(), rvon_mises(), etc, and if needed, wrappers around them for generating data according to a design matrix. Perhaps we can figure out a way to generate data based on a model formula?

Oh, that makes me think that we could potentially be using the stan models with prior_only to sample from priors on which we set the parameters. That samples in seconds, but compilation takes a while. I'll check if we can somehow avoid compilation of a model when changing priors (I think I've seen that somewhere)

**Comment by GidonFrischkorn** [comment]
I will also clos this, as we have done so for all implemented models and we have another issue for generating the simExperiment function.

**Comment by venpopov** [comment]
in the future you can do that automatically, by writing `Closes #32` somewhere in the text of the pull request, and you can list as many of those as you like
