### ISSUE TITLE
Make sure to run check() before commit package changes

### ISSUE THREAD

**Issue by venpopov** [venpopov/bmm#34]
I just submitted a pull request for the sdm functions. Before that I followed 5.2 from https://github.com/stan-dev/stan/wiki/Developer-process-overview#52--steps-for-pull-requests to merge the development branch into my feature branch to ensure there are no conflicts.  Before I did that, check() reported that the package works well, but afterwards I got one error and several notes:

![image](https://github.com/venpopov/bmm/assets/12783882/ddbcebd4-41af-4aac-9f22-51a419b95719)

I will fix these and open a separate pull request to keep things independent. But in the future please make sure that check() returns no problems before commit changes @GidonFrischkorn

**Comment by GidonFrischkorn** [comment]
Sure, will check for the next commits.
________________________________
Von: Ven Popov ***@***.***>
Gesendet: Tuesday, January 30, 2024 5:24:59 PM
An: venpopov/bmm ***@***.***>
Cc: Gidon Frischkorn-Bartsch ***@***.***>; Mention ***@***.***>
Betreff: [venpopov/bmm] Make sure to run check() before commit package changes (Issue #34)


I just submitted a pull request for the sdm functions. Before that I followed 5.2 from https://github.com/stan-dev/stan/wiki/Developer-process-overview#52--steps-for-pull-requests to merge the development branch into my feature branch to ensure there are no conflicts. Before I did that, check() reported that the package works well, but afterwards I got one error and several notes:

image.png (view on web)<https://github.com/venpopov/bmm/assets/12783882/ddbcebd4-41af-4aac-9f22-51a419b95719>

I will fix these and open a separate pull request to keep things independent. But in the future please make sure that check() returns no problems before commit changes @GidonFrischkorn<https://github.com/GidonFrischkorn>
