### ISSUE TITLE
Is "log(inv_ss)" correction needed for the IMM?

### ISSUE THREAD

**Issue by venpopov** [venpopov/bmm#36]
I'm working through the code, and I noticed that for the 3-parameter model, [we correct the theta estimates for setsize](https://github.com/venpopov/bmm/blob/8c1f3c05bfb370de4b3cac3a206b423410926f1e/R/fit_model.R#L180C96-L180C106):

``` r
brms::nlf(stats::as.formula(paste0(theta_nts[i], ' ~ ', lure_idx_vars[i],
                                                     '*(thetant + log(inv_ss)) + (1-', lure_idx_vars[i], ')*(-100)')))
```

but we [don't do it for the IMM](https://github.com/venpopov/bmm/blob/8c1f3c05bfb370de4b3cac3a206b423410926f1e/R/fit_model.R#L254C1-L254C130):

``` r
brms::nlf(stats::as.formula(paste0(theta_nts[i], ' ~ ', lure_idx_vars[i], 
                                                     '*(a) + (1-', lure_idx_vars[i], ')*(-100)')))
```

I don't remember if we talked about this - @GidonFrischkorn is it not necessary for the IMM? For the 3-parameter it was needed so that theta_nt is on the same scale regardless of how many non-target options there are. Seems to me that should also be the case for the IMM, but you'll know better than me

**Comment by GidonFrischkorn** [comment]
The IMM explicitly does not weigh the activation by the number of before normalization. This is highlighted in the Appendix of the Oberauer et al. (2017) paper in Journal of Vision. 

So, I would keep it the way it is implemented now. This way "a" in the IMM represents the general activation of one non-target item and the probability of non-target intrusion results by multiplying the general activation by the number of non-target items:

$$ P_{nt} = \frac{N_{nt} * e^a}{e^b + N_{nt} * e^a + e^{c+a}} $$

or alternatively:

$$ P_{nt} = \frac{e^{a+log(N_{nt})}}{e^b + e^{a + log(N_{nt})} + e^{c+a}} $$
