### ISSUE TITLE
Create custom summary.bmmfit method 

### ISSUE THREAD

**Issue by venpopov** [venpopov/bmm#37]
Currently the brms model returns a summary that include the internal terms such as constant mu, kappa2, etc

![image](https://github.com/venpopov/bmm/assets/12783882/401950a0-ca13-4e2d-9ad8-8dc28f88a3f0)

We can remove that with a bit of preprocessing - brms does the same internally for its own models.

**Comment by GidonFrischkorn** [comment]
Just to remind ourselves of the discussion we had today: We will implement this by writing a `summary.bmmfit` method to avoid changing any information in the fit object and keep it compatible with most of the brms post-processing.

**Comment by venpopov** [comment]
Yes, just as an example of why we really want to do this. I had never run the mixture3p model when there is setsize 1. We did anticipate it and fixed the thetant to be a constant for setsize1, but if I didn't know why, I would be quite confused by this output:

![image](https://github.com/venpopov/bmm/assets/12783882/2d69d977-fcd4-4398-846e-de0530c54006)

**Comment by venpopov** [comment]
Before we dive into doing this, mayb discuss what we would like the summary to actually show.

For example, here's the summary from an example sdm model

![image](https://github.com/venpopov/bmm/assets/12783882/07fdd176-67b5-40ff-b6a2-175ad8d812b4)

For this particular model it actually mostly fine. I'd prefer to have it show
- mu_Intercept instead of Intercept, in line with our discussion of making all parameters explicit
- show the bmm formula instead of the brms formula
- keep the constant mu parameter, since it is part of the model that users can predict if they want
- perhaps move it to a new section called "Fixed parameters:" right under Regression Coefficients:, to avoid confusion

So my proposal for all models is:
- Change "Family:" to "Model:" and display the name of the bmm model
- Replace the formula with the bmmformula
- In regression coefficients, keep only the estimated parameters.
- In a new section "Fixed parameters", show SOME of the fixed parameters. For all models that will be:
     - mu or mu1
     - other potentially important parametrs. For the mixture3p this is thetant_SetSize1, because it is important to know if you try to calculate the p_mem and p_nt for all conditions. But you don't need to know mu5 and kappa5, since those are just tricks to use a VM distribution as a uniform. Perhaps also print "thetaguess", which is always 0, but makes it explicit. We can discuss how best to do that programmatically - maybe a part of the model info that specifies which parameters to include in the summary

**Comment by venpopov** [comment]
Just a few notes about how brms produces the summary. Assume `fit` is the variable containing the model fit

- when you type `fit` into the console, it:
     - call the generic print() method
     - since fit is of class 'brmsfit', this calls print.brmsfit(), which is a simple fuction, ensuring that print produces the summary, so it's the same as calling summary(fit):
```
function (x, digits = 2, ...) 
{
    print(summary(x, ...), digits = digits, ...)
}
```

- this then calls summary.brmsfit(), which produces a list (e.g. see `str(summary(fit))`) with class 'brmsummary`
- since the function above has one more print inside it, it calls print.brmssummary, which determines how the information from the summary object is displayed.

### what do we need?

- we don't need print.bmmfit, since print.brmsfit will still work and call the generic summary(x,...) command
- we also don't need a complete rewrite of summary.brmsfit. We can have a function summary.bmmfit, which roughly looks like this:

```r
summary.bmmfit <- function(object, priors = FALSE, prob = 0.95, robust = FALSE,  mc_se = FALSE, ..., backend = 'bmm') {
   # add some check about possible backends (bmm and brms only)

   # get summary object from brms, since it contains a lot of necessary information:
   out <- NextMethod('summary')

   # stop and give brms summary if user wants brms summary
   if (backend == 'brms') {
    return(out)
   }

   # out is just a list - at this point we can modify it any way we want. In a upcoming PR I have also saved the bmm model and bmm_formula objects in the output, so we can access them for info
   # here add, remove or change any parts of the summary list

   # assign bmmsummary class to handle the printing
   class(out) <- 'bmmsummary'
   out
}
```

and then a custom print.bmmsummary method (modifying the base code from brms:::print.brmssummary)


------------------


I think this will be the simplest approach

**Comment by GidonFrischkorn** [comment]
Agreed! If you want you can have a look at it. I took the more complicated road and actually looked into writing a whole summary.bmmfunction.

But I think given that we import brms your suggestion will work easiest.

I did not make much progress so far. So, if you want to feel free to have a look into this. I will get to this earliest by Tuesday or Wednesday next week.

**Comment by venpopov** [comment]
Ok, then if you don't mind I will give it ago :)
