### ISSUE TITLE
require dependent variable to be passed to the model to avoid specifying it in the formula

### ISSUE THREAD

**Issue by GidonFrischkorn** [venpopov/bmm#79]
- dv as required argument
- add option to predict the location of the target distribution in the mixture models

**Comment by venpopov** [comment]
one solution to the problem you told me at lunch would be write a bmm formula function similar to brms::bf, in which we have more flexibility, though I suspect this might be a lot of work and not sure if it's worth it. Just an idea

**Comment by venpopov** [comment]
although maybe we should stick with the current syntax to be consistent with brms

**Comment by GidonFrischkorn** [comment]
Yes, I thought a bit about possible solutions as well, but did not come up with one yet. I will have to look into this in more detail for the ezDM implementations anyway. But for now, I would keep the formula syntax the way it is.

**Comment by GidonFrischkorn** [comment]
I have looked a bit into the object created by the `brmsformula` function. And think there might be an easier solution than initially thought to this problem. I will explore it a little, but in short. The `bf` function separates the first formula as the "main" formula and stores the rest of the formulas in an additional list labeled `pforms`. I assume this is an abbrehviation for parameter formulas.

I think it should be possible to write a simple `bmm_formula` function that creates this list taking in the same type of formulas that the `brmsformula` function takes in. And then we can actually just add the correctly formatted list into the `formula$pforms` list. 

I will check this out at the beginning of next week and keep you updated.

**Comment by venpopov** [comment]
that's along the lines of what I was thinking above. Glad to hear it is simpler than expected!

**Comment by GidonFrischkorn** [comment]
I had a bit of time to look into this and thing I should be able to provide a solution. This also entails checking if formulas for all model parameters were specified and throwing a warning if this is not the case while only estimating a fixed intercept for them.

I will keep you posted on the progress and then we can see, if the solution seems feasible for all models and also in the long run.

But for some models, such as The ezDM, I will certainly use this functionality. So, I will keep exploring this anyway.
