### ISSUE TITLE
pre-processing for `mixture3p` and `IMM` model fails if the setsize variable contains character information

### ISSUE THREAD

**Issue by GidonFrischkorn** [venpopov/bmm#97]
When I tested the `mixture3p` model for the Vignette on the mixture models using the Bayes data set from the `mixtur` package, I noticed that the preprocessing and creating of the Index variables fails, because the variable is coded as `Set Size 1`, `Set Size 2`, `Set Size 4`, and `Set Size 6`.

We should include a notification that the setsize variable should be coded either numerically, if it is entered as a continuous predictor, or with factor labels that only use single digits. Alternatively, we could see if we can remove all alphabet letters from the set size labels to only maintain the digit information. But this would also fail, if someone uses labels such as "one", "two", "three", etc. for coding a set size factor.

**Comment by GidonFrischkorn** [comment]
if we want to remove the letters from the labels we could use: `gsub('[[:alpha:] ]', '', labels)`

**Comment by venpopov** [comment]
good catch. I think best to keep it simply. Requere it to be either numeric, or coercible to numeric (digits as factors). I'll add that as a stop condition and test

**Comment by venpopov** [comment]
Now that I tested it, this is even a bigger issue - if you have a factor with labels such as "Set size 1", "...2", "...4" and "...8", the current code would translate it as set size 1,2,3, and 4 and never give an error. The model would have run, and the results would have been plausible, but still wrong! 

> **So we should really take this as an example of what to think about and what to test for when transofrming any data from the user.**

**Comment by venpopov** [comment]
fixed by https://github.com/venpopov/bmm/commit/be789f6b6d75db735e2f87889b12031e4d3916b4
