### ISSUE TITLE
Proposal to rename imm/3p arguments

### ISSUE THREAD

**Issue by venpopov** [venpopov/bmm#98]
I've been thinking about this for a while, and now is a good time to bring it up - to me spaPos is unintuitive as an argument. Without reading the documentation it sounds like it asks for the position of non_targets, whereas it asks for the distance. 

Can I suggest renaming this to spa_dist? More generally, both non_targets and spaPos refer to different features of the non_targets relative to the target. So mayb we should consider something like nt_features/nt_values and nt_dists. That is, I'm suggesting renaming:

`non_targets` to `nt_features` or `nt_values`
`spaPos` to `nt_dists`

makes it consistent with the parameter naming (thetant), and makes it clear what type of information each contains and how they are related.  Alows opens up the positibility to expand it naturally in the future if we want to allow people to specify multiple distance metrics via nt_dists1, nt_dists2, ntdists3, etc... The model doesn't care what they represent and it would be up to the user to interpret within the context of whatever distance they are using. What do you think?

**Comment by GidonFrischkorn** [comment]
Agreed. I have renamed them in #92 commit [e9c12dd](https://github.com/venpopov/bmm/pull/92/commits/e9c12dd6985f27249b44edc1cdbc375fff292071)

non_targets to nt_features, and
spaDist to nt_distance

Generally, I think having the labels a little bist longer and as intuitive as possible will help users a lot.
